### ISSUE TITLE
Running docker on the same machine where the game is running

### ISSUE THREAD

**Issue by ghost** [bankjaneo/XivMitmDocker#1]
Any chance this could run on the same machine where the game is running? Maybe using a [static IP](https://stackoverflow.com/a/39498534)?. Since this is docker can this be run on Docker for Windows as well? I successfully connected to a linux VM hosted on a windows host in the past and I've been trying to move to a docker method for some times. It's nice to see someone has been working on it

**Comment by bankjaneo** [comment]
I haven't tried that yet. But I believe in can be done if VM is using Bridged Adapter from the host.

But for Docker Desktop on Windows that is using WSL2 through NAT, I think it's not possible.

**Comment by ghost** [comment]
I see. I was planning to move XivMitmLatencyMitigator on my home server anyway so this issue might not affect me in the future but it would be nice to finally replace the Hyper-V method proposed on the main repo with a docker container. I also tried setting a static IP on WSL2 in the past but no matter what windows and linux failed to communicate. I guess this should be put on hold till WSL2 updates with a proper working method..
