### ISSUE TITLE
Docker on archlinux

### ISSUE THREAD

**Issue by Kashozs** [bankjaneo/XivMitmDocker#2]
Hello bankjaneo.
I wanted to ask can i download docker on archlinux installation media ? Because i tried the docker command line and it says

 bash: docker: command not found 

 Sorry im new to this ^^

**Comment by ghost** [comment]
Try installing docker with `sudo pacman -Sy docker docker-compose`

**Comment by Kashozs** [comment]
> Try installing docker with `sudo pacman -Sy docker docker-compose`

I tried it but it dosent work with sudo but it managed to work without sudo only pacman, at the end of downloading it stops and says something about corrupt files i don't know why

Thanks in advance

Edit: with sudo it says 
 
bash: sudo: command not found

**Comment by ghost** [comment]
You are probably running out of memory. Are you trying to use the same virtual machine from [the old repo](https://github.com/Soreepeong/XivMitmLatencyMitigator)? The docker method is meant to be used on a normally installed operative system. The original method runs entirely on your RAM without writing anything on your disk. It only uses 256MB so you'll completely run out of memory if you try to also install docker in that space

**Comment by ghost** [comment]
@Kashozs You might not need the docker method. This repo already offers the mitigate.py script with the fixes applied so you could curl the one on this repo instead. You'd basically follow the [original guide](https://github.com/Soreepeong/XivMitmLatencyMitigator) but using the fixed script url instead.
```bash
# Make sure you remove prior leftover files
rm ./definitions.json ./ffxiv.exe
# Download new static one from this repo
wget https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/ffxiv.exe
wget https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/definitions.json
# Fetch and run the mitigate.py script from this repo instead of the main one
curl https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/mitigate.py | python
```

**Comment by bankjaneo** [comment]
This docker way shouldn't be using with any Linux that run on installation media. Try the original method instead but with modified mitigate.py and definitions.json as @steponmepls suggested.

**Comment by Kashozs** [comment]
> @Kashozs You might not need the docker method. This repo already offers the mitigate.py script with the fixes applied so you could curl the one on this repo instead. You'd basically follow the [original guide](https://github.com/Soreepeong/XivMitmLatencyMitigator) but using the fixed script url instead.
> 
> ```bash
> 
> # Make sure you remove prior leftover files
> 
> rm ./definitions.json ./ffxiv.exe
> 
> # Download new static one from this repo
> 
> wget https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/ffxiv.exe
> 
> wget https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/definitions.json
> 
> # Fetch and run the mitigate.py script from this repo instead of the main one
> 
> curl https://raw.githubusercontent.com/bankjaneo/XivMitmDocker/main/app/mitigate.py | python
> 
> ```
Hi 

I tried your idea but when i type the second code it gives me this
![image](https://user-images.githubusercontent.com/107314363/212484681-252204e6-3fa9-48a7-bdb4-d5d0815c402d.jpeg)

Also when i type the curl command it says this
![image](https://user-images.githubusercontent.com/107314363/212484736-8cb4f9b3-c561-4567-b641-601fb764a2b5.jpeg)

I also managed to install archlinux and downloadid the docker but when i type the docker command it says this
![image](https://user-images.githubusercontent.com/107314363/212484876-5c2619c1-9fd5-4b10-8205-8868e8988eb0.jpeg)

Thanks. @steponmepls @bankjaneo

**Comment by ghost** [comment]
`definitions.json` has been deleted from the repo because the maintainer integrated the [hotfixes](https://github.com/Soreepeong/XivMitmLatencyMitigator/issues/73#issuecomment-1382663731) that now work with the 6.3 `ffixv.exe` so by trying to fetch that URL you'll get a 404 file not found.

As always, follow the guide on the main repo, use an Arch installation iso and once you are at the part where you `curl <script-url> | python` use the following forked script instead
```
https://raw.githubusercontent.com/xzn/XivMitmLatencyMitigator/main/mitigate.py
```

**Comment by bankjaneo** [comment]
For the script, please use new URL as @steponmepls mentioned. The original method on main repo is back to working again with new script URL.

For the docker, I have no experience on Arch but from your screenshot, it looks like docker daemon is not running. You might want to try follow step 2 and 4 on this website https://www.linuxfordevices.com/tutorials/linux/install-docker-on-arch.

You can skip step 3 since you are already running as root user by default.
