### ISSUE TITLE
Docker in a laptop in the same network

### ISSUE THREAD

**Issue by Pox4ever** [bankjaneo/XivMitmDocker#3]
Hi, sorry to bother you about this, but I am trying to run your container on my laptop and after routing on my gaming PC the FFXIV doesn't connects.

Before anything, are these errors ok to happen on the log?
![image](https://user-images.githubusercontent.com/2739506/212430493-1cbc0665-e14b-4401-8f33-58744b7c0a8a.png)

**Comment by bankjaneo** [comment]
These errors are fine. It's from oodle things in the original script.

For connection problem, try trace route your game server after set the route command on Windows to see if game traffic went through your laptop IP or not.

You can find your game server IP at [Is FFXIV Up](https://is.xivup.com/adv).

If it's still not working, please show your docker run command or docker-compose.yml file.

**Comment by bankjaneo** [comment]
~~Just tested for you. I think local network routing is not working now. I usually ran it through VPN. I'll let you know again once it fixed.~~

Checked and found nothing wrong with iptables script in the container.

Please make sure that you enable `net.ipv4.ip_forward=1` on your Linux.

Use this 1 line command to enable and reboot.

```
sudo sed -i "s/#net.ipv4.ip_forward/net.ipv4.ip_forward/" /etc/sysctl.conf && sudo sysctl -p && reboot
```

Or do it manually by
1. Edit the file `/etc/sysctl.conf` and find the line with net.ipv4.ip_forward=1
2. Uncomment this line by removing `#`
3. Save and exit.
4. Run this command `sysctl -p`
5. Reboot.

**Comment by Pox4ever** [comment]
I feel bad that I've cut that part off of the screenshot, 
![image](https://user-images.githubusercontent.com/2739506/212448117-31ae8232-aa20-4ab5-86a0-edae1f50ef81.png)

So it is probably that, I will test very soon. Thank you very much for the information and for making this nice docker container!

**Comment by Pox4ever** [comment]
It worked perfectly!

Thank you very much again for the help and the container!
