### ISSUE TITLE
Raspberry Pi 400 - ARM64 question

### ISSUE THREAD

**Issue by Pox4ever** [bankjaneo/XivMitmDocker#4]
Hi!
I've tried to install this on a Raspberry Pi 400 by changing to the arm64 correct version of docker and using qemu to emulate the amd64 platform but it didn't work.

Do you happen to have a arm64 version of this container?

I'm trying it because I wanted to leave the raspberry pi close to the router connected to an ethernet cable.

I am not sure if the issue is really about the architecture, but I think it might.
This is the log:
![Screenshot from 2023-01-22 14-05-52](https://user-images.githubusercontent.com/2739506/213920003-2503b182-533d-4e43-adfa-34d7abc9cf3a.png)

**Comment by bankjaneo** [comment]
For now, I don't have the ARM64 version yet. May I ask if the traditional method works on your Pi before?

**Comment by Pox4ever** [comment]
> For now, I don't have the ARM64 version yet. May I ask if the traditional method works on your Pi before?

I am trying now, having a hard time to make python run the x86 binary file though. I'll update you soon, for some reason the `apt install g++ gcc-multilib g++-multilib` doesn't work on the Ubuntu ARM64

**Comment by Pox4ever** [comment]
Yeah, it doesn't work, guess I'm doomed :(

**Comment by bankjaneo** [comment]
I read that it used to work on ARM before oodle things come into play, about 7 months ago, i guess.

If you happen to find a way to make it work, please let me know and I'll instantly build a new container for those Pi users :)

**Comment by Pox4ever** [comment]
I managed to make the oodler helper running using your docker image, but now I'm trying to fix the
`Failed to initialize nft: Protocol not supported`

**Comment by Pox4ever** [comment]
Almost giving up lol, couldn't manage to create iptables on the docker. It looks like it doesn't load the host module because I'm sort of using qemu to run oodle. I think it is possible though, I'm just too dumb for it hahaha

I'll continue the research on the weekend

**Comment by bankjaneo** [comment]
Maybe you should try with normal version to get it working first (if it can). Then I can apply it to docker version.

**Comment by igor-antonio** [comment]
Oodle and exe are x86 structures so it isn't compatible with raspi, I tried even installing a x86 emulator on this.
