### ISSUE TITLE
Issue zoning in after logging in using docker container

### ISSUE THREAD

**Issue by aurilain** [bankjaneo/XivMitmDocker#5]
So, I have the docker running and I was having great success with it until 6.35. I play on PS5.

I have internet access on PS% that has a LAN connection connected to the virtual machine. I am able to log into ffxiv and go thru character selection, but when I try to actually zone in the game just hangs there and I get an Error 10105.

I downloaded the newest version of ffxiv.exe using HFS into my Debian VM.

I use the docker container. not compose. Also I am a linux noob.

What am I missing?

**Comment by bankjaneo** [comment]
There are a lot of updates needed for 6.35. I have done all of them and update the docker image already.

What you need to do now stop the container, delete your current bankja/xivlm:latest image and start the container again so it will download the latest version for you.

**Comment by aurilain** [comment]
I successfully stopped the container using the command line in the readme. How do I delete the current bankja/xivlm:latest image? Will starting the container again remove and reinstall it?

**Comment by bankjaneo** [comment]
If you are certain that you are not using docker-compose to run. Copy and paste this command will get you everything you need. Then start the container again.

`sudo docker stop xiv-mitm-latency-mitigator && sudo docker rm xiv-mitm-latency-mitigator && sudo docker rmi bankja/xivlm:latest`

This command assumes that your container name is `xiv-mitm-latency-mitigator` same as in the example.

**Comment by aurilain** [comment]
This worked. Thank you.
