### ISSUE TITLE
Help needed setting up on Steam Deck

### ISSUE THREAD

**Issue by shingonati0n** [bankjaneo/XivMitmDocker#7]
Hello, first and foremost, thanks for building this docker! I'm currently trying to make this work on a Steam Deck. I was able to install and run Docker on it - but probably need some more help setting this up due to the fact I'm running the game and the container on the same system. What I've tried so far - 

1. Run your docker - it executes fine from what I saw. I noticed this doesn't have an IP though:

`(deck@steamdeck run)$ docker inspect xiv-mitm-latency-mitigator[
    {
        "Id": "5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad",
        "Created": "2024-07-03T17:20:28.143570448Z",
        "Path": "bash",
        "Args": [
            "/app/entrypoint.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1985,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-07-03T17:20:28.587202443Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:b0f9d5cd98d6185c0f269e07d9f499efdac8783137df30cc38faa12ae177222f",
        "ResolvConfPath": "/var/lib/docker/containers/5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad/hostname",
        "HostsPath": "/var/lib/docker/containers/5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad/hosts",
        "LogPath": "/var/lib/docker/containers/5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad/5b644597aac973b45dbd192211e580709c6aef1be4f36433f5d23c18b5ee03ad-json.log",
        "Name": "/xiv-mitm-latency-mitigator",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                51,
                121
            ],
            "CapAdd": [
                "NET_ADMIN"
            ],
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d622a8fc0146ea7c1cf8b4502a883455819234714c69ca40dafdaa0a961b2d69-init/diff:/var/lib/docker/overlay2/c575d7e20d3e7d812eb7f91dee700684084b7cd0100693fd0d1b6438963b054a/diff:/var/lib/docker/overlay2/4a77379b75a8225beaf402e95904e37a60ea4fe3ea7f21e9a491b88a8a592a95/diff:/var/lib/docker/overlay2/03f35daa059b5e4b868c03ff6809b452e5d229ca03e048e0fb7dbb1a6a315c30/diff:/var/lib/docker/overlay2/79f350b3bad7b6e74b754dc4485d51c8821e832c0a1f1cf7674c1c64da3b9241/diff:/var/lib/docker/overlay2/a6765ad4c094a9200d1012461b361ee470ed9910e7893c8221a58ff8d270ad72/diff",
                "MergedDir": "/var/lib/docker/overlay2/d622a8fc0146ea7c1cf8b4502a883455819234714c69ca40dafdaa0a961b2d69/merged",
                "UpperDir": "/var/lib/docker/overlay2/d622a8fc0146ea7c1cf8b4502a883455819234714c69ca40dafdaa0a961b2d69/diff",
                "WorkDir": "/var/lib/docker/overlay2/d622a8fc0146ea7c1cf8b4502a883455819234714c69ca40dafdaa0a961b2d69/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "colima",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MITIGATOR=true",
                "LOCAL=false",
                "LEGACY=false",
                "EXTRA_DELAY=0.150",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "bankja/xivlm:latest",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "bash",
                "/app/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "22.04"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "94374df6425e538a9337538a98719cf39a6caeaa9846f1a11668a0d207a3cb81",
            "SandboxKey": "/var/run/docker/netns/default",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "",
                    "NetworkID": "17b485f4892cdf6a36b3f5903ae4b99f1f2dd52fd461bc1256ccba0978647344",
                    "EndpointID": "6143666a2b40f337965e5b849dc6e89e85223e7fbfac8c0dd1dbb014e9033606",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": null
                }
            }
        }
    }
]
`

2. I figured since both game and docker are on the same system, I could route to the same IP being used. by the Steam Deck. This doesn't work - the game fails when connecting with error 2002. 
3. Before going with your docker I was trying to build something similar to this with podman, but couldn't give the container an IP under the same network I am (something that was suggested here: https://github.com/Soreepeong/XivMitmLatencyMitigator/issues/43). Can you guide me on how to achieve this with this docker?? Thanks again!!

**Comment by shingonati0n** [comment]
UPDATE: I was able to run your docker using podman, and even have connectivity - I ended using the default podman bridge which has I/O connectivity, however the game still crashes with error 2002 :/ This is how I ran it:

`podman run -d \
  --name=xiv-mitm-latency-mitigator \
  --restart=unless-stopped \
  --net=podman \
  --cap-add=NET_ADMIN \
  -e MITIGATOR=true \
  -e LOCAL=true \
  -e LEGACY=false \
  -e VPN=false \
  -e EXTRA_DELAY=0.150 \
  docker://bankja/xivlm:latest`

and then routed the IPs to the podman ip:

`sudo ip route add 124.150.157.0/24 via 10.88.0.2
sudo ip route add 153.254.80.0/24 via 10.88.0.2
sudo ip route add 202.67.52.0/24 via 10.88.0.2
sudo ip route add 204.2.29.0/24 via 10.88.0.2
sudo ip route add 80.239.145.0/24 via 10.88.0.2
`

I ran `podman logs -f mitm-xiv-latency-mitigator` too to check if things were being picked up and saw movement when pressing start - however the game crashed with 2002. I think all info got logged, but didn't noted where the logs were saved in the container to extract them. I'll try to do so and report back.

**Comment by bankjaneo** [comment]
You're welcome and thank you for using my docker :)

But to run XivMitmLatencyMitigator, you unfortunately need another machine to make it working. It's not possible to run on the game machine due to network routing limitation. If you run XivMitmLatencyMitigator and FFXIV on the same machine, after `ip route add`, the game packet will travel in circle and not going out to the Internet.

**Comment by shingonati0n** [comment]
Thanks for getting back, in the end I ran the script directly as per the full instructions on another machine. For this to work on Steam Deck it still needs some tweaking. For starters, to make the routing work on Game Mode, Decky Loader is needed; this so we can use Decky Terminal plugin, which allow us to enter the bash commands for the ip route. I still think this could be a self contained solution for Linux using podman, for will probably look at that another time.

**Comment by bankjaneo** [comment]
I think this may be possible with macvlan on the container. But I don't have gaming linux machine to test. Just an idea 😊

**Comment by shingonati0n** [comment]
Exciting news, I DID IT! I was able to run the code from Steam Deck using podman and some ipvlan trickery. I'll test stability and will work on implementation. More to come soon 😃

**Comment by bbnuy** [comment]
that's amazing, could you please offer us a little bit of insight? i apologize, i'm not much beyond a beginner but i believe others will benefit from it! i've struggled to set it up on my steamdeck and at the moment i have no other machine to play ffxiv on (my ping is ~220ms on a good day)

**Comment by bankjaneo** [comment]
Since I don't have any gaming Linux machine to test but I think this might be possible with macvlan. You could try this simple code to test it out and please give me a result if it not working and let's see if I can fix it or not.

**Proceed with caution! This may break your current xivlm if you've done anything wrong and don't know how to fix it.**

**Step 1**: Create docker network for macvlan

```
docker network create -d macvlan --subnet=<LAN_SUBNET> --gateway=<GATEWAY_IP> -o parent=<INTERFACE> macvlan0
```

Edit `<LAN_SUBNET>`, `<GATEWAY_IP>`, `<INTERFACE>` to match with your network and system. Or you can use the lazy command below, I believe it should work in most cases.

```
docker network create -d macvlan --subnet=$(ip route | grep $(ip route get 8.8.8.8 | awk -- '{printf $5}') | grep -v default | awk -- '{printf $1}') --gateway=$(ip route | grep default | awk -- '{printf $3}') -o parent=$(ip route get 8.8.8.8 | awk -- '{printf $5}') macvlan0
```

**Step 2**: Stop and remove existing container if you already have it running. Then modify the docker-compose.yml file. Change network from host to macvlan. Change `<XIVLM_IP>` to any static IP you want based on your network. And use `docker-compose up -d` to get it up

```
services:
  xivlm:
    container_name: xiv-mitm-latency-mitigator
    image: bankja/xivlm:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      macvlan0:
        ipv4_address: <XIVLM_IP>
```

**Step 3**: This should get XivMitmLatencyMitigator up and running with its own IP instead of host IP. Now route game traffic to this new IP instead by following `Step 9` at [https://github.com/Soreepeong/XivMitmLatencyMitigator](https://github.com/Soreepeong/XivMitmLatencyMitigator) (I think the original guide is also outdated, the list of IPs need to be updated.)

**Remove any game related existing routes before proceed further, if you have any.**

Anyway, for Linux use these commands. It already contains all updated IP range. Don't forget to change the IP from `<XIVLM_IP>` to match with your IP from previous step.

```
sudo ip route add 109.244.0.0/16 via <XIVLM_IP>
sudo ip route add 119.252.36.0/24 via <XIVLM_IP>
sudo ip route add 119.252.37.0/24 via <XIVLM_IP>
sudo ip route add 153.254.80.0/24 via <XIVLM_IP>
sudo ip route add 80.239.145.0/24 via <XIVLM_IP>
sudo ip route add 162.14.0.0/16 via <XIVLM_IP>
sudo ip route add 27.221.0.0/16 via <XIVLM_IP>
sudo ip route add 119.97.0.0/16 via <XIVLM_IP>
sudo ip route add 204.2.29.0/24 via <XIVLM_IP>
sudo ip route add 183.111.189.0/24 via <XIVLM_IP>
```

**_To undone everything. Use these commands._**

Remove game routing to `<XIVLM_IP>`

```
sudo ip route delete 109.244.0.0/16 via <XIVLM_IP>
sudo ip route delete 119.252.36.0/24 via <XIVLM_IP>
sudo ip route delete 119.252.37.0/24 via <XIVLM_IP>
sudo ip route delete 153.254.80.0/24 via <XIVLM_IP>
sudo ip route delete 80.239.145.0/24 via <XIVLM_IP>
sudo ip route delete 162.14.0.0/16 via <XIVLM_IP>
sudo ip route delete 27.221.0.0/16 via <XIVLM_IP>
sudo ip route delete 119.97.0.0/16 via <XIVLM_IP>
sudo ip route delete 204.2.29.0/24 via <XIVLM_IP>
sudo ip route delete 183.111.189.0/24 via <XIVLM_IP>
```

Stop and remove container and delete macvlan network

```
docker-compose down
docker network rm macvlan0
```

**Comment by shingonati0n** [comment]
These are more or less the steps I followed, but some comments: 

- Although it's possible to create a network with macvlan (it won't complain at all), it will timeout immediately when trying to to connect to it using wlan0 as the adapter. Seems macvlan doesn't work well with wifi adapters, hence the reason I used ipvlan instead - ipvlan does allow to connect via wifi (wlan0) without issues. The only catch is that the ip address must be statically assigned. This is one of the things I'm trying to solve to create an installer of sorts. In the case of Steam Deck, I'm also positive wifi will be used rather than ethernet.
- The main drawback of ipvlan on rootful is that it will allow you connect other to other machines and even the internet except the host and viceversa. The workaround solution I had to this was to add a couple of routes on both the Deck and the container to link the default network bridge that comes with podman with the ip assigned by ipvlan: 

(on the Deck) sudo ip route add  <XIVLM_IP> via <podman_network_bridge>
(on the container) sudo ip route add < Deck IP> via <podman_network_bridge>

This meant the container needs to be attached to 2 networks: 

the one created with ipvlan
the default podman bridge

this is because the default bridge network allows the very same communication ipvlan doesn't: host and container and viceversa.
 
- The container you need to create must have some additional options:

services:
  xivlm:
    container_name: xiv-mitm-latency-mitigator
    image: bankja/xivlm:latest
    cap_add:
      - NET_ADMIN,**NET_RAW**
  **--sysctl net.ipv4.ip_forward=1**
  **--sysctl net.ipv4.conf.all.route_localnet=1**
    restart: unless-stopped
    networks:
      macvlan0:
        ipv4_address: <XIVLM_IP>

The ones in bold are needed, without them the container cannot do forwarding properly or even ping hosts.

EDIT: I also missed stating, when setting the routes for the game Ip's do it thru the **network bridge ip and not ipvlans!**

`sudo ip route add 109.244.0.0/16 via <podman_network_bridge_ip>
sudo ip route add 119.252.36.0/24 via <podman_network_bridge_ip>
sudo ip route add 119.252.37.0/24 via <podman_network_bridge_ip>
sudo ip route add 153.254.80.0/24 via <podman_network_bridge_ip>
sudo ip route add 80.239.145.0/24 via <podman_network_bridge_ip>
sudo ip route add 162.14.0.0/16 via <podman_network_bridge_ip>
sudo ip route add 27.221.0.0/16 via <podman_network_bridge_ip>
sudo ip route add 119.97.0.0/16 via <podman_network_bridge_ip>
sudo ip route add 204.2.29.0/24 via <podman_network_bridge_ip>
sudo ip route add 183.111.189.0/24 via <podman_network_bridge_ip>`

On the mitigator.py script the commands to flip the ip_forward and route_localnet have to be commented since they will be inherent to the container. 

The setup is not easy lol, I was building some scripts to make the process easier and willl be posting them on my hub when ready. Right now in testing there is only one bug which I think is kinda scary - when exiting the game directly while the container is running somehow corrupts the exit state of the game. If you try to enter again while connecting to the mitigator, the container somehow starts sending connections like crazy and the game crashes with the infamous error 10105, and after a min, the Deck freezes and crashes. 

So far I discovered that you need to follow these steps when stopping playing: 

- do not exit game, select "log out" instead
- on the title screen go to Konsole or Decky Terminal and stop the container (with sudo podman stop <container_name>) , clean the ip routes as the comment above
- log in with no mitigator on - and then exit the game. 

I was checking the mitigator.py script to check where the loop is being caused and try to handle it differently. Once I have that sorted out I'll publish something basic to make this thing work. Again, this bug is pretty scray if you are not used to these kinda things. In the meantime, let me know if you have questions or comments.

**Comment by bankjaneo** [comment]
This is cool! Wish you success with ipvlan method. This might help many FFXIV Linux player.

Anyway, I did some more research and found that the default docker firewall rules prevent host to communicate with container that using macvlan. There is a work around for that with these commands. However, like I already mentioned, I don't have any machine to test so this is purely based on hypothesis.

```
ip link add macvlan0-bridge link ens18 type macvlan mode bridge
ip addr add <XIVLM_IP_TO_USE_FOR_ROUTE>/32 dev macvlan0-bridge
ip link set macvlan0-bridge up
ip route add <XIVLM_IP>/32 dev macvlan0-bridge
```

Set another static IP for bridge interface `<XIVLM_IP_TO_USE_FOR_ROUTE>`. This will create a bridge interface that allow docker host to communicate with macvlan docker. However, these command does not persist on reboot. (Another problem, but not hard. Let's get it working first.)

For routing part.

```
sudo ip route add 109.244.0.0/16 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 119.252.36.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 119.252.37.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 153.254.80.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 80.239.145.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 162.14.0.0/16 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 27.221.0.0/16 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 119.97.0.0/16 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 204.2.29.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
sudo ip route add 183.111.189.0/24 via <XIVLM_IP_TO_USE_FOR_ROUTE>
```

---

And here is the correct docker-compose.yml file, I guess.

```
services:
  xivlm:
    container_name: xiv-mitm-latency-mitigator
    image: bankja/xivlm:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    networks:
      macvlan0:
        ipv4_address: <XIVLM_IP>
```

**Comment by bbnuy** [comment]
i appreciate your replies! i actually hadn’t expected to be answered posthaste, thank you very much! i fear, however, i may be a lost case; as much as i could progress through the guides you both kindly explained in detail, i couldn’t complete my setup successfully. probably expected as a beginner, i still apologize for not being able to provide much feedback… i will have access to my steamdeck in a few days so i could do a more in-depth reply, if needed, but i doubt my unexperienced blunders will be of much import for you two. of course, i’m available for further feedback if so needed. i probably should wait for shing0nation’s scripts, i wish i were more reckless and knowledgeable to be of help to you, bankjaneo. i’m very thankful for your continued help! i in fact didn’t expect any replies as it’s a rather niche issue. i thank you for your time and apologize for my shortcomings

**Comment by shingonati0n** [comment]
Further Updates: I pinpointed the issue I notified last time and in the end is related to IPVlan. 

BTW, I tested macvlan and works great.... as long as you are connected via cable. It does DHCP and since it has its own MAC address it works smoothly. However for Steam Deck, being the portable console it is, I'm pretty sure the majority of players, like myself, use it on wifi, which as I stated before doesn't work with macvlan :( . Where I am with IPVLAN then?? The issue stems from the fact IPVlan uses the same MAC address as the host system (in this case the Steam Deck). The problem comes from the fact the router assumes the ip of the steam deck is the containers (which is assigned statically) until at some point it either expire the lease of the IP and reassigns the DHCP assigned IP back. That's when the container doesn't connect and sends connections in an endless loop. I'm currently researching how to setup IPVlan correctly to handle this scenario. Man, I wish macvlan would also work with wifi. Once I have this solved, I'll probably reach out to seek help testing.

**Comment by bankjaneo** [comment]
I have to admit that I completely forgot about the portability perspective. The best solution should work anywhere, with any Wi-Fi connection. This makes it even more challenging. If I come up with any ideas, I'll let you know. :)

However, I doubt that it is a network layer limitation to achieve this.

Back in my raid days, I rent a $5/mt AWS Lightsail instance and route game traffice via ZeroTier to it for both XIVMitmLatencyMitigator and reduce ping for my static. This can solved everything but it come with a price.

**Comment by shingonati0n** [comment]
More updates - I think you are right on the limitation not being in the network. I think in the end the IPVlan solution was more of an accidental thing rather than something proper. Right now I'm trying to go using the podman bridge network and so far I can send data to the container, but loops endlessly inside. Will report back once I figure out that part.

**Comment by shingonati0n** [comment]
(Hopefully) Final Update: I finallymade this work consistently - and you won't believe it, the solution does require IPVlan + bridge network: 

- After reading a lot of sites and spread documentation, I now know that a virtual interface will never be able to communicate with its parent interface - that's the reason Mac/IPVlan won't work alone - the hst data will never reach the container properly
- This is where the podman default bridge network comes into play - the bridge network is not a child interface to wlan0
- Besides the container ipvlan a host ipvlan interface is needed - this will give us the way out of the continer into the internet
- So we set both on the container. The communication goes something like this:

Host -> podman(or docker) default network bridge -> Container -> podman ipvlan/macvlan -> host ipvlan/macvlan interface -> internet

Another thing that I discovered, was that the endless loop tends to happen when the connections are established; most of times when initiating  the container, the internet on the ipvlan won't connect as quick - so for my process, I inserted a couple of gate steps in between, so instead of running the container directly, I follow these step in sequence:

1. Create container using create instead of run, using the default network bridge as network
2. Create and connect ipvlan network
3. start container
4. run iptables 
5. run ping to one of the game servers - if ping does not respond, it means the connection is not established - I repeat this until  I get a ping response from the game servers
6. Only when step 5 succeeds i run the mitigator script - and then the game trafic gets routed correctly. 

I'm currentl writing the README and adding a couple of customization options. My image of the podman container is already out there in quay.io. @bbnuy I'll reach out to you - need a tester for this, mostly to ensure this work on any Deck - mine's full of custom things and want to be extra sure before releasing. @bankjaneo  thanks for your replies, and also for your feedbacks, some of your pointers did help a lot! I'm closing this as complete.

**Comment by shingonati0n** [comment]
@bbnuy reach out to me via discord pls - my discord is Ugo#8690 or ugo_f5

**Comment by shingonati0n** [comment]
Epilogue: @bankjaneo - https://github.com/shingonati0n/xivomega

**Comment by bankjaneo** [comment]
> Epilogue: @bankjaneo - https://github.com/shingonati0n/xivomega

This is very neat. Congratulation for the fruit of your hard work!! This will be very handy for those Linux gamers who has only 1 computer/device.

Btw, I like the naming scheme. lol. The next coming public useful project might be XIVEden 😄
