### ISSUE TITLE
›TimeoutError: time out

### ISSUE THREAD

**Issue by efraim9000** [bankjaneo/XivMitmDocker#8]
I'm running the docker logs -f command to look. I just built a fresh VM to try and run your code. I keep getting the following error when connecting to the game.

<img width="1279" alt="Screenshot 2024-07-31 at 1 28 26 PM" src="https://github.com/user-attachments/assets/65940665-ba2e-4b4c-9ec0-0eecafda9f03">

Any idea what it might be? I've followed your instructions to a T. Hopefully it's not negligence on my part.

**Comment by bankjaneo** [comment]
Normally this problem can come from

- VM built-in firewall problem
- ffxiv_dx11.exe needed to be updated.

I personally retired from FFXIV but by friends are still using my docker and they haven't report any problem (yet). So I suspect the firewall rule.

Could you try set environment variable `MITIGATOR=false` and try enter game again? This will disable the XivMitmLatencyMitigator but still allow you to route game traffic through VM. If it's still not working then the problem should be from firewall rule.

Anyway, could you please post your `docker run` command or `docker-compose.yml` file content here too?

**Comment by hammypants** [comment]
> Normally this problem can come from
> 
>     * VM built-in firewall problem
> 
>     * ffxiv_dx11.exe needed to be updated.
> 
> 
> I personally retired from FFXIV but by friends are still using my docker and they haven't report any problem (yet). So I suspect the firewall rule.
> 
> Could you try set environment variable `MITIGATOR=false` and try enter game again? This will disable the XivMitmLatencyMitigator but still allow you to route game traffic through VM. If it's still not working then the problem should be from firewall rule.
> 
> Anyway, could you please post your `docker run` command or `docker-compose.yml` file content here too?

I'm seeing this on my own version of a dockerized xivmitm as well as yours. I had a question for you, though:

> Then you have to route game traffic to this virtual machine by following step 10 at https://github.com/Soreepeong/XivMitmLatencyMitigator

All of your sample configuration runs on a `host` configured `network_mode` in docker. Why, then, is the route game traffic step required? How are you routing game traffic when the container network adapters are the same as the host?

**Comment by bankjaneo** [comment]
Using `host` network mode due to port of the XivMitmLatencyMitigator is random so you don't have to manually forward ports (If I remember correctly). You can try docker network if you want as long as the game client can see the port it needs to connect to.

Both original XivMitmLatencyMitigator script or this dockerized version needs to run on separated machine that is not your game machine in order for routing traffic to work.

**Comment by hammypants** [comment]
> Using `host` network mode due to port of the XivMitmLatencyMitigator is random so you don't have to manually forward ports (If I remember correctly). You can try docker network if you want as long as the game client can see the port it needs to connect to.
> 
> Both original XivMitmLatencyMitigator script or this dockerized version needs to run on separated machine that is not your game machine in order for routing traffic to work.

@bankjaneo Hey, first, thanks for replying.

Reading your answer made me realize I misread/misinterpreted parts of [XivMitmLatencyMitigator](https://github.com/Soreepeong/XivMitmLatencyMitigator)'s documentation, which then lead me to a source code dive. (Which I probably should have done anyway.)

Long story short, it can work on the same host machine (yours probably can, too), as long as you keep in mind your note about it being a "separate machine," emphasis on the air quotes. Some people probably VM it. I got mine to work with a separate ipvlan + post-routing.

Anyway, thanks again.
